export const ROUTES = {
    HOME: "/",
    LOGIN: '/login',
    REGISTER: '/register',
    SETUP_PIN: '/setup-pin',
    DASHBOARD: '/dashboard',
    INTERNAL_TRANSFER: '/transfer/internal',
    SWIFT_TRANSFER: '/transfer/swift',
    TRANSACTION_HISTORY: '/history/:accountId',
    KLIK_CODE: '/klik/code',
    ADD_JUNIOR: '/junior/add',
    CARDS: '/cards',
    JUNIOR_APPROVALS: '/junior/approvals',
    MANAGE_JUNIOR: '/junior/:accountId/manage',
    EXTERNAL_TRANSFER: '/transfer/external',
    KLIK_P2P: '/transfer/klik',
    SETTINGS: '/settings',
    AML_HOLDS: '/aml/holds',
    AML_ADMIN: '/aml/admin',
};