spring.application.name=bank-a
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.check-location=false
logging.level.org.flywaydb=DEBUG

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank_a}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bank_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secretpassword}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

integration.elixir.base-url=${ELIXIR_BASE_URL:http://elixir-service:8080}
app.elixir.poll-interval-ms=30000

integration.klik.base-url=${KLIK_BASE_URL}
integration.klik.api-key=${KLIK_API_KEY}
integration.klik.zone=${KLIK_ZONE:PL}

integration.cards.grpc-host=${CARDS_GRPC_HOST:card-provider-service}
integration.cards.grpc-port=${CARDS_GRPC_PORT:50051}
integration.cards.gateway-url=${CARDS_GATEWAY_URL:http://payment-gateway-service:8000}

integration.express.base-url=${EXPRESS_BASE_URL:http://elixir-express-service:8082}
integration.sorbnet.base-url=${SORBNET_BASE_URL:http://sorbnet-service:8083}
app.bank.bicfi=${BANK_BICFI:BANK_A}
app.bank.sorbnet-account=${BANK_SORBNET_ACCOUNT:SORBNET-A-00000000000000000001}
app.bank.elixir-account=${BANK_ELIXIR_ACCOUNT:ELIXIR-A-00000000000000000001}
# Karty Płatnicze
integration.cards.gateway-url=${CARDS_GATEWAY_URL:http://cards_gateway_app:8000}
integration.cards.api-key=${CARDS_PROVIDER_API_KEY:bank-key-pl-a}
integration.cards.hmac-secret=${CARDS_PROVIDER_HMAC_SECRET:secret-pl-a-hmac}
integration.cards.bin-prefix=${CARDS_PROVIDER_BIN:410001}
integration.cards.request-timeout-ms=10000
integration.cards.admin-key=${CARDS_PROVIDER_ADMIN_KEY:admin-secret-key-2026}

# SWIFT
integration.swift.base-url=${SWIFT_BASE_URL:http://host.docker.internal:3000}
integration.swift.client-id=${SWIFT_CLIENT_ID:bank-plbkpl01}
integration.swift.client-secret=${SWIFT_CLIENT_SECRET:secret-plbkpl01}
integration.swift.bic=${SWIFT_BIC:PLBKPL01XXX}
integration.swift.callback-url=${SWIFT_CALLBACK_URL:http://polish-bank-a:8000/api/webhooks/swift/receive}
integration.swift.request-timeout-ms=10000
integration.swift.delivery-scheduler-ms=86400000
